# Generated by Django 6.0.2 on 2026-02-22 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('supplier', models.CharField(blank=True, max_length=255, null=True)),
                ('new_input_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('new_output_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('new_wholesale_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childern', to='product.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.TextField(blank=True, null=True)),
                ('input_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('output_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('wholesale_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('barcode', models.CharField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/product/images')),
                ('stock', models.IntegerField(default=0)),
                ('min_stock', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='product_category', to='product.category')),
            ],
        ),
    ]
