# Generated by Django 6.0.2 on 2026-02-22 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='product_shop', to='shop.shop'),
        ),
        migrations.AddField(
            model_name='productinput',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_input', to='product.product'),
        ),
    ]
