# Generated by Django 6.0.2 on 2026-02-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='shop/images')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('currency', models.CharField(choices=[('usd', 'AQSH dollari'), ('uzs', "O'zbekiston so'mi"), ('rubl', 'Rossiya rubli')], default='uzs', max_length=20)),
                ('tax', models.IntegerField(default=0)),
                ('created_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
